"""Anonymous GitHub readback of the current accepted source and native artifact."""
import hashlib,json,subprocess,urllib.request,datetime,sys
from pathlib import Path
folder=Path(__file__).resolve().parent
root=folder.parents[1]
commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip()
base='https://api.github.com/repos/AnasSarkiz/tscircuit-ai-agent-remote'
def get(url,raw=False):
    request=urllib.request.Request(url,headers={'User-Agent':'board-publication-verification','Accept':'application/vnd.github.raw+json' if raw else 'application/vnd.github+json'})
    with urllib.request.urlopen(request,timeout=45) as response:
        data=response.read()
        return data if raw else json.loads(data)
repo=get(base)
assert repo['private'] is False
remote_commit=get(base+'/commits/main')['sha']
assert remote_commit==commit, (commit,remote_commit)
tree=get(base+'/git/trees/'+commit+'?recursive=1')
assert not tree['truncated']
blobs={item['path']:item['sha'] for item in tree['tree'] if item['type']=='blob'}
manifest=json.loads((folder/'final-package-inputs.json').read_text())
compared=[]
for item in manifest['files']:
    name=item['path']
    # Registry package metadata is explicitly generated by the packaging helper.
    if name=='package.json':continue
    data=(root/name).read_bytes()
    local_blob=hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest()
    assert blobs[name]==local_blob,name
    compared.append(name)
raw=get(base+'/contents/dist/index/circuit.json?ref='+commit,raw=True)
assert raw==(root/'dist/index/circuit.json').read_bytes()
record={'checked_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'anonymous_public_repo':repo['private'] is False,'commit':commit,'main_head_matches':True,'compared_root_source_model_docs_native_files':len(compared),'all_compared_git_blob_hashes_match':True,'native_raw_exact_bytes_match':True,'native_sha256':hashlib.sha256(raw).hexdigest(),'package_metadata_transform':'package.json generated by scripts/prepare-board-package.ts; same dependency versions and overrides verified separately.','url':repo['html_url']+'/commit/'+commit}
(Path(sys.argv[1]) if len(sys.argv)>1 else folder/'github-public-readback.json').write_text(json.dumps(record,indent=2)+'\n')
print(json.dumps(record))
