"""Bind the latest actual WIP without inventing public delivery or passing gates."""
import hashlib,json,subprocess
from pathlib import Path
folder=Path(__file__).resolve().parent;root=folder.parents[1];rel=str(folder.relative_to(root));p=root/'context/build-checkpoint.json';j=json.loads(p.read_text());raw=(root/'dist/index/circuit.json').read_bytes();sha=hashlib.sha256(raw).hexdigest()
def read(n):return json.loads((folder/n).read_text())
checks=read('artifact-checks.json');assert next(x for x in checks if x['name']=='schema-and-paste')['exit_code']==0
j.update(native_build=rel+'/final-schematic-native/circuit.json',sha256=sha,size_bytes=len(raw),traces=381,vias=320,native_pours=273,native_open_port_errors=50,physically_open_nets=12,unassigned_required_battery_contacts=2,unconnected_required_contacts=52,measured_geometry_violations=0,measured_shorts=0,fabrication_ready=False,current_local_version='0.0.11-wip-generator-qualification',native_traces_below_explicit_source_minimum=0,native_traces_below_named_net_nominal_requiring_review=65,current_board_test_pass_count=51,current_board_test_failure_count=1,routing_regression_pass_count=99,schema_failures=0,missing_paste_records=0,strict_supplier_rotation_qualified=True,strict_supplier_rotation_blocker=None,U14_exact_download_missing_paste_pads=0,supplier_confirmed_stock_covers_identities=39,supplier_inventory_unknown_identities=0,supplier_positive_overseas_count_identities=42,supplier_public_buyability_covers_identities=39,supplier_zero_public_buyability=['C94934'],supplier_out_of_stock=['C94934'],supplier_assembly_eligibility_unconfirmed=['C2913201','C54313','C364359'],current_supplier_stock_verified=False,current_supplier_stock_checked=True,all_current_supplier_parts_available=False,all_26_schematic_pages_visually_reviewed=False,publication_runtime_cli_build_seconds=read('final-schematic-native-build.log.outcome.json')['elapsed_seconds'],publication_runtime_cli_build_passed=False,publication_runtime_cli_build_error_count=50,completed_publication_runtime_cli_build=True,publication_runtime_physical_records_identical=True,publication_runtime_frozen_install_passed=True,current_publication_source_matches_checked_runtime=True,public_fields_describe_parent_until_new_publication_verified=True)
for key,name in {'latest_order_readiness_review':'review.md','latest_accepted_correction':'review.md','accepted_source_snapshot':'final-schematic-native/completed-source-and-phases.tar.gz','source_checks_receipt':'final-source-checks/source-checks.json','code_checks_receipt':'artifact-checks.json','native_qualification_receipt':'schematic-source-physical-preservation.json','latest_actual_srj':'actual-native.srj.json','resolved_bom_receipt':'resolved-bom-receipt.json','schematic_component_coverage_receipt':'guide-coverage.json','latest_schematic_annotation_review':'guide-coverage.json','supplier_stock_receipt':'official-stock/receipt.json','supplier_stock_interpretation':'current-stock-application.json','supplier_current_identity_binding_receipt':'current-stock-application.json','dated_stock_identity_binding':'current-stock-application.json','ui_schematic_style_receipt':'ui-analysis/ui-style-analysis-receipt.json','ui_schematic_style_issue_receipt':'ui-analysis/ui-style-analysis-receipt.json','cloud_setup_receipt':'setup-smoke/receipt.json','supervisor_smoke_receipt':'setup-smoke/receipt.json'}.items():j[key]=rel+'/'+name
j['canonical_runtime_provenance']='toolchain/provenance.json';j['canonical_pill_paste_generator_fix']={'applied_to_current_board':True,'provenance':'toolchain/provenance.json','schema_and_paste_receipt':rel+'/schema-and-paste.json'}
j['limitations']=['50 native J7/U27 connection errors / 12 assigned physical open nets plus two unassigned J3 contacts (52 required contacts unresolved).','No final qualified 2.8-inch LCD, backlight, flex mating/bend/RF geometry or final battery outer polarity.','65 nominal net-width differences need individual current/electrical qualification; no whole-board thermal/impedance approval.','D2 C94934 out of stock; three positive-stock parts have unconfirmed assembly eligibility. No assembler allocation.','One retained UI parallel-branch alignment advisory and unchanged source snapshot references remain; no fabrication, order or hardware-test approval.','Running network policy lacks saved manufacturer hosts; draft saving does not apply runtime configuration.']
ui=read('ui-analysis/ui-style-analysis-receipt.json');j.update(ui_schematic_style_check_executed=ui.get('run_style_analysis_clicked',False),ui_schematic_style_issues=ui.get('issue_count'),ui_schematic_style_passed=ui['ui_schematic_style_passed'],ui_schematic_style_blocker='Actual latest UI results retained; no style waiver.')
snapshot=read('source-snapshot.log.outcome.json');j.update(source_entry_snapshot_completed=snapshot['completed_command'],source_entry_snapshot_termination=snapshot['termination'],source_entry_snapshot_seconds=snapshot['elapsed_seconds'],source_entry_snapshot_passed=snapshot['exit_code']==0,publication_runtime_snapshot_completed=snapshot['completed_command'],publication_runtime_snapshot_passed=snapshot['exit_code']==0,publication_runtime_snapshot_seconds=snapshot['elapsed_seconds'],publication_runtime_schematic_snapshot_passed=snapshot['exit_code']==0,publication_runtime_snapshot_receipt=rel+'/source-snapshot.log.outcome.json',source_entry_snapshot_receipt=rel+'/source-snapshot.log.outcome.json')
j.update(U14_exact_download_import_applied_to_board=True, stationary_purchased_world_geometry_unchanged=125, actual_purchased_pose_preservation_receipt=rel+'/schematic-source-physical-preservation.json', supplier_refresh_warning_review=rel+'/final-retained-metadata-review.json', fresh_physical_copper_receipt=rel+'/current-copper-audit.json', fresh_connected_pair_preservation_receipt=rel+'/current-connection-preservation.json', schematic_source_style_repair_receipt=rel+'/schematic-style-repair/final-label-clearance-source-change.json', cloud_configuration_saved_revision=32, cloud_configuration_save_receipt=rel+'/cloud-configuration-save-receipt.json', cloud_configuration_applied=False, cloud_environment_published=False, generation_runtime='Bun 1.4.0', frozen_install_and_test_runtime='Bun 1.3.9', generation_runtime_setup_script='scripts/cloud/setup-generation-runtime.sh')
j.update(publication_runtime_physical_records_identical=False, publication_runtime_physical_geometry_identical=True, retained_optional_metadata_delta_receipt=rel+'/final-retained-metadata-review.json', remaining_native_error_receipt=rel+'/remaining-native-errors.json', native_runtime_completed_receipt=rel+'/final-schematic-native-build.log.outcome.json', native_runtime_timing_telemetry_verified=False)
p.write_text(json.dumps(j,indent=2)+'\n')
