export function BoardNets() {
  return (
    <>
      <net name="AMP_BCLK" />
      <net name="AMP_DIN" />
      <net name="AMP_LRCLK" />
      <net name="AMP_SD_MODE" />
      <net name="AUDIO_ENABLE_SUPPLY" />
      <net name="AUDIO_NMOS_GATE" />
      <net name="AUDIO_PMOS_GATE" />
      <net name="BACKLIGHT_GATE" />
      <net name="BUCK_ENABLE" />
      <net name="CHARGER_ILIM" />
      <net name="CHARGER_ISET" />
      <net name="CHARGE_PGOOD_N" />
      <net name="CHARGE_STATUS_N" />
      <net name="GND" isGroundNet />
      <net name="HAPTIC_N" />
      <net name="HAPTIC_NMOS_GATE" />
      <net name="HOLD_BUFFER_OUT" />
      <net name="HOLD_HARDWARE" />
      <net name="LCD_BACKLIGHT_OUTPUT" />
      <net name="LCD_BACKLIGHT_RETURN" />
      <net name="LCD_CS_N" />
      <net name="LCD_DC" />
      <net name="LCD_ENABLE" />
      <net name="LCD_RESET_N" />
      <net name="LCD_SCLK" />
      <net name="LCD_SDA" />
      <net name="MCU_AUDIO_BCLK" />
      <net name="MCU_AUDIO_DIN" />
      <net name="MCU_AUDIO_ENABLE" />
      <net name="MCU_AUDIO_LRCLK" />
      <net name="MCU_BACKLIGHT_PWM" />
      <net name="MCU_BOOT_N" />
      <net name="MCU_EN" />
      <net name="MCU_HAPTIC_ENABLE" />
      <net name="MCU_HOLD_READ" />
      <net name="MCU_LCD_CS_N" />
      <net name="MCU_LCD_DC" />
      <net name="MCU_LCD_RESET_N" />
      <net name="MCU_LCD_SCLK" />
      <net name="MCU_LCD_SDA" />
      <net name="MCU_MIC_BCLK" />
      <net name="MCU_MIC_WS" />
      <net name="MCU_RESET_N" />
      <net name="MCU_UART_RX" />
      <net name="MCU_UART_TX" />
      <net name="MCU_USB_DN" />
      <net name="MCU_USB_DP" />
      <net name="MIC_BCLK" />
      <net name="MIC_BCLK_INPUT" />
      <net name="MIC_INPUT" isPowerNet />
      <net name="MIC_SD" />
      <net name="MIC_SD_BUFFERED" />
      <net name="MIC_SD_REF" />
      <net name="MIC_WS" />
      <net name="MIC_WS_INPUT" />
      <net name="PACK_BAT" isPowerNet />
      <net name="PACK_NTC" />
      <net name="REG_FB" />
      <net name="REG_PG" />
      <net name="SERVICE_UART_TX" />
      <net name="SPEAKER_N" />
      <net name="SPEAKER_P" />
      <net name="USB_CC1" />
      <net name="USB_CC2" />
      <net name="USB_DN" />
      <net name="USB_DP" />
      <net name="V3V3" isPowerNet />
      <net name="VBUS" isPowerNet />
      <net name="VLCD" isPowerNet />
      <net name="VMIC" isPowerNet />
      <net name="VMOTOR" isPowerNet />
      <net name="VSYS" isPowerNet />
    </>
  )
}
