"""Bind the actual accepted source, stock, native and unsuppressed gate receipts."""
from pathlib import Path
import json,hashlib,collections,decimal
folder=Path(__file__).resolve().parent
native_path=Path('dist/index/circuit.json');payload=native_path.read_bytes();native=json.loads(payload);sha=hashlib.sha256(payload).hexdigest()
read=lambda name:json.loads((folder/name).read_text())
audit=read('final-copper-audit.json');preservation=read('contact-migration-preservation.json');poses=read('stationary-geometry.json');layers=read('final-native-compliance.json')
assert sha==audit['source_sha256']==preservation['after_native_sha256']==poses['after_sha256']==layers['native_sha256']
assert audit['drc_violation_count']==0 and audit['short_count']==0 and poses['passed'] and preservation['preserved_under_explicit_interface_migration']
regions=[read(f'{name}-region-widths.json') for name in ['connection','power','inner']]
assert all(r['source_sha256']==sha and r['failed_region_count']==0 for r in regions)
errors=[r for r in native if 'error' in r['type']]
components={r['pcb_component_id']:r for r in native if r['type']=='pcb_component'};names={r['source_component_id']:r['name'] for r in native if r['type']=='source_component'}
breakdown=collections.Counter(names[components[r['pcb_component_ids'][0]]['source_component_id']] for r in errors)
(folder/'remaining-native-errors.json').write_text(json.dumps({'native_sha256':sha,'count':len(errors),'by_component':dict(breakdown),'raw_errors':errors,'all_connections_complete':False},indent=2)+'\n')
parts={r['name']:(r['manufacturer_part_number'],r['supplier_part_numbers']['jlcpcb'][0]) for r in native if r['type']=='source_component' and r.get('supplier_part_numbers',{}).get('jlcpcb')}
stock=read('official-stock/receipt.json');stockparts={name:(r.get('model'),r['part_number']) for r in stock['results'] for name in r['references']}
assert parts==stockparts
binding={'current_native_sha256':sha,'stock_source_native_sha256':stock['source_sha256'],'purchased_components':len(parts),'supplier_identities':len(stock['results']),'every_current_reference_exact_mpn_and_supplier_matched':True,'inventory_scope':'Exact official overseasStockCount, canPresaleNumber and public library flags. Neither field proves assembler allocation, global warehouse totals or a reserved order.','positive_reported_overseas_count_identities':sum(r['stock_count']>=len(r['references']) for r in stock['results']),'positive_public_buyability_count_identities':stock['covered_parts'],'zero_or_insufficient_public_buyability':[{'part':r['part_number'],'references':r['references'],'overseasStockCount':r['stock_count'],'canPresaleNumber':r['available_to_buy']} for r in stock['results'] if not r['stock_covers_one_board']],'all_assembly_available':False,'fabrication_ready':False}
(folder/'dated-stock-application.json').write_text(json.dumps(binding,indent=2)+'\n')
prices=[]
for r in stock['results']:
 price=decimal.Decimal(str(r['stock_record']['initialPrice']));assert price.is_finite() and price>=0
 prices.append({'part':r['part_number'],'references':r['references'],'quantity':len(r['references']),'reference_unit_usd':str(price),'extended_usd':str(price*len(r['references'])),'public_standalone_pre_min_purchase':r['stock_record'].get('preMinPurchaseNum'),'public_least_patch_number':r['stock_record'].get('leastPatchNumber')})
cost={'native_sha256':sha,'dated_source':'official-stock/receipt.json','reference_component_subtotal_usd':str(sum(decimal.Decimal(r['extended_usd']) for r in prices)),'included_purchased_placements':125,'included_supplier_identities':43,'is_order_quote':False,'excludes':['PCB','assembly/setup','shipping/tax','external purchased assemblies','MOQ/allocation effects'],'parts':prices}
(folder/'current-reference-cost.json').write_text(json.dumps(cost,indent=2)+'\n')
widths=read('trace-widths.json');schema=read('schema-audit-summary.json');ui=read('ui-analysis/ui-style-analysis-receipt.json');snapshot=read('source-snapshot.log.outcome.json')
summary={'version':'0.0.9-wip-standard-uart','native_sha256':sha,'native_bytes':len(payload),'native_source_filesystem_md5':next(r['source_filesystem_md5_hash'] for r in native if r['type']=='source_project_metadata'),'native_traces':sum(r['type']=='pcb_trace' for r in native),'native_vias':layers['via_count'],'native_pours':sum(r['type']=='pcb_copper_pour' for r in native),'native_errors':len(errors),'native_error_breakdown':dict(breakdown),'measured_shorts':audit['short_count'],'measured_geometry_violations':audit['drc_violation_count'],'physically_open_nets':audit['physically_open_net_count'],'required_active_regions_width_checked':sum(r['checked_region_count'] for r in regions),'required_active_region_width_failures':0,'retained_contact_pairs_checked':preservation['connected_pairs_checked'],'retained_contact_losses':len(preservation['lost_connections']),'stationary_purchased_geometries':poses['stationary_purchased_geometry_count'],'sole_purchased_replacement':'J6/C160389','purchased_component_pose_moves':0,'full_through_vias_0p30_hole_0p45_land':layers['ordinary_vias_exact_0p30_hole_0p45_pad_full_span'],'high_current_native_traces_checked':layers['high_current_native_trace_count'],'high_current_regions_checked':layers['high_current_active_source_trunk_regions'],'high_current_trunks_outer_only':layers['high_current_native_traces_outer_only'] and layers['high_current_regions_outer_only'],'source_checks_passed':read('accepted-source-checks/source-checks.json')['passed'],'routing_regression_pass_count':94,'board_test_pass_count':49,'board_test_fail_count':2,'schematic_ui_style_issues':ui['issue_count'],'schematic_ui_style_passed':ui['ui_schematic_style_passed'],'strict_schema_failures':schema['failing_elements'],'snapshot_completed':snapshot['completed_command'],'snapshot_passed':snapshot['exit_code']==0,'snapshot_references_updated':False,'native_trace_widths_checked':widths['checked_trace_count'],'native_wire_segments_checked':widths['checked_wire_segment_count'],'native_traces_below_board_minimum':widths['trace_count_below_board_minimum'],'native_traces_below_explicit_source_minimum':widths['trace_count_below_source_minimum'],'native_traces_below_named_net_nominal':widths['trace_count_below_net_nominal'],'latest_reference_component_subtotal_usd':cost['reference_component_subtotal_usd'],'publications_verified':False,'requested_display_implemented':False,'full_zero_DRC_and_connectivity_pass':False,'fabrication_ready':False,'programming_hardware_tested':False}
(folder/'final-qualification-summary.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary))
