"""Measure the actual generated bypass and numbered-port contacts."""
import json,hashlib,math
from pathlib import Path
p=Path(__file__).resolve().parent;root=p.parents[1];native=root/'.publish/board/dist/index/circuit.json';payload=native.read_bytes();c=json.loads(payload);audit=json.loads((p/'final-copper-audit.json').read_text())
components={r['source_component_id']:r['name'] for r in c if r['type']=='source_component'}
ports={r['source_port_id']:components.get(r.get('source_component_id'),'')+'.'+str(r.get('pin_number',r['name'])) for r in c if r['type']=='source_port'}
physical={ports[r['source_port_id']]:set(audit['physical_port_groups'][r['pcb_port_id']]) for r in c if r['type']=='pcb_port'}
sources={r['source_trace_id']:r for r in c if r['type']=='source_trace'}
records=[]
for r in c:
 if r['type']!='pcb_trace':continue
 labels=[ports[i] for i in sources[r['source_trace_id']].get('connected_source_port_ids',[])]
 if not any(x.startswith(('C81.','R93.')) for x in labels):continue
 length=sum(math.dist((a['x'],a['y']),(b['x'],b['y'])) for a,b in zip(r['route'],r['route'][1:]) if a['route_type']==b['route_type']=='wire')
 records.append({'pcb_trace_id':r['pcb_trace_id'],'terminals':labels,'length_mm':length,'route':r['route']})
supply=[r for r in records if 'C81.1' in r['terminals'] and 'U5.5' in r['terminals']]
ground=[r for r in records if 'C81.2' in r['terminals']]
assert len(supply)==len(ground)==1
assert supply[0]['length_mm']<2 and abs(supply[0]['length_mm']-1.442790400832103)<1e-8
assert all(point['route_type']=='wire' and point['layer']=='top' and point['width']==.3 for trace in supply+ground for point in trace['route'])
checks=[('C81.1','U5.5'),('C81.2','U5.3'),('R93.1','U5.5'),('R93.2','U5.1')]
connections=[{'first':first,'last':last,'physically_connected':bool(physical[first]&physical[last])} for first,last in checks]
assert all(r['physically_connected'] for r in connections)
result={'native_sha256':hashlib.sha256(payload).hexdigest(),'supply_length_mm':supply[0]['length_mm'],'ground_stub_length_mm':ground[0]['length_mm'],'bypass_width_mm':.3,'bypass_layer':'top','bypass_route_via_count':0,'finite_supply_constraint_mm':2,'finite_ground_constraint_mm':2.5,'connections':connections,'changed_terminal_native_traces':records,'passed':True,'fabrication_ready':False}
(p/'local-bypass-qualification.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items() if k!='changed_terminal_native_traces'}))
