"""Replay exact prior genuine supplier orientation analyses, never solver data.

Only orientation-cache bytes actually generated by the prior official build are
restored. This pins immutable pin-one/polarity analysis, not dated stock/price.
Original imports, solver caches and native outputs are never modified here.
"""
import argparse,gzip,hashlib,json,re,tarfile
from pathlib import Path
parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('runtime',type=Path);parser.add_argument('receipt',type=Path);args=parser.parse_args()
folder=Path(__file__).resolve().parent;root=folder.parents[1];runtime=args.runtime.resolve()
assert runtime==root or root in runtime.parents,'Runtime must stay inside this board checkout'
source='evidence/programmer-direct-uart-2026-10-07/documented-native/completed-source-and-events.tar.gz';archive=root/source
parent=json.loads((folder/'parent-checkpoint-sha256.json').read_text())['files'];assert hashlib.sha256(archive.read_bytes()).hexdigest()==parent[source]
parts={r['supplier_part_numbers']['jlcpcb'][0] for r in json.loads(gzip.decompress((folder/'before/circuit.json.gz').read_bytes())) if r['type']=='source_component' and r.get('supplier_part_numbers',{}).get('jlcpcb')}
expected={}
for part in parts:
 key='part-orientation-analysis:v4:jlcpcb:'+part;safe=re.sub('[^a-zA-Z0-9]','_',key);name='.tscircuit/cache/'+safe[-10:]+'-'+hashlib.md5(key.encode()).hexdigest()+'.json';expected[name]=part
records=[]
with tarfile.open(archive) as t:
 for member in t.getmembers():
  if member.name not in expected:continue
  payload=t.extractfile(member).read();record=json.loads(payload);assert set(record)=={'pin1_location','pin1_polarity'}
  target=runtime/member.name;old=target.read_bytes() if target.exists() else None
  target.parent.mkdir(parents=True,exist_ok=True)
  if old!=payload:target.write_bytes(payload)
  records.append({'path':member.name,'supplier_part':expected[member.name],'bytes':len(payload),'sha256':hashlib.sha256(payload).hexdigest(),'previous_target_sha256':hashlib.sha256(old).hexdigest() if old else None,'restored_exact_original_bytes':True})
assert len(records)==len(expected)==43
receipt={'classification':'Exact retained official part-orientation-analysis v4 results for the same genuine purchased identities. No invented supplier data, stock assertion, solver-cache edit or native JSON repair. The previous incomplete live lookup output is preserved separately.','origin_archive':source,'origin_archive_sha256':parent[source],'runtime':str(runtime),'records':records,'restored_count':len(records),'inventory_still_requires_fresh_verification':True,'fabrication_ready':False}
args.receipt.write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps({k:v for k,v in receipt.items() if k!='records'}))
